import type { LanguageCode } from '../shared/types'
import type { Phrase, PhraseCategory, PhraseMode, SubtextMode } from './types'

export const LANGUAGES: Record<LanguageCode, string> = {
	ja: '日本語',
	en: 'English',
	es: 'Español',
	fr: 'Français',
	de: 'Deutsch',
	pt: 'Português',
}

export const CATEGORY_LABELS: Record<PhraseMode, string> = {
	motivation: 'Daily Motivation',
	affirmation: 'Affirmations',
	haiku: 'Haiku',
	word: 'Word of the Day',
	custom: 'Custom',
}

export const SUBTEXT_MODE_LABELS: Record<SubtextMode, string> = {
	none: 'None',
	translation: 'Translation',
	romaji: 'Romaji',
	custom: 'Custom',
}

export const MOTIVATIONS: Phrase[] = [
	{
		id: 'perseverance',
		romaji: 'Ippo ippo, mae e susumu',
		texts: {
			ja: '一歩一歩、前へ進む',
			en: 'Step by step, moving forward',
			es: 'Paso a paso, avanzando',
			fr: 'Pas à pas, avancer',
			de: 'Schritt für Schritt vorwärts',
			pt: 'Passo a passo, seguindo em frente',
		},
	},
	{
		id: 'growth',
		romaji: 'Hibi seichō',
		texts: {
			ja: '日々成長',
			en: 'Growing every day',
			es: 'Creciendo cada día',
			fr: 'Grandir chaque jour',
			de: 'Jeden Tag wachsen',
			pt: 'Crescendo a cada dia',
		},
	},
	{
		id: 'mindfulness',
		romaji: 'Ima wo ikiru',
		texts: {
			ja: '今を生きる',
			en: 'Live in the present',
			es: 'Vivir el presente',
			fr: 'Vivre le présent',
			de: 'Im Moment leben',
			pt: 'Viver o presente',
		},
	},
	{
		id: 'strength',
		romaji: 'Nana korobi ya oki',
		texts: {
			ja: '七転び八起き',
			en: 'Fall seven times, rise eight',
			es: 'Cae siete veces, levántate ocho',
			fr: 'Tomber sept fois, se relever huit',
			de: 'Siebenmal fallen, achtmal aufstehen',
			pt: 'Cair sete vezes, levantar oito',
		},
	},
	{
		id: 'persistence',
		romaji: 'Keizoku wa chikara nari',
		texts: {
			ja: '継続は力なり',
			en: 'Persistence is power',
			es: 'La persistencia es poder',
			fr: 'La persévérance est le pouvoir',
			de: 'Beharrlichkeit ist Stärke',
			pt: 'Persistência é poder',
		},
	},
	{
		id: 'beginners-mind',
		romaji: 'Shoshin wasuru bekarazu',
		texts: {
			ja: '初心忘るべからず',
			en: "Never forget beginner's mind",
			es: 'Nunca olvides la mente del principiante',
			fr: "N'oublie jamais l'esprit du débutant",
			de: 'Vergiss nie den Geist des Anfängers',
			pt: 'Nunca esqueça a mente de iniciante',
		},
	},
	{
		id: 'one-meeting',
		romaji: 'Ichi-go ichi-e',
		texts: {
			ja: '一期一会',
			en: 'One time, one meeting',
			es: 'Un momento, un encuentro',
			fr: 'Une fois, une rencontre',
			de: 'Eine Zeit, eine Begegnung',
			pt: 'Um momento, um encontro',
		},
	},
	{
		id: 'action',
		romaji: 'Yūgen jikkō',
		texts: {
			ja: '有言実行',
			en: 'Words into action',
			es: 'Palabras en acción',
			fr: 'Des paroles aux actes',
			de: 'Worte in Taten umsetzen',
			pt: 'Palavras em ação',
		},
	},
	{
		id: 'challenge',
		romaji: 'Chōsen suru yuuki',
		texts: {
			ja: '挑戦する勇気',
			en: 'Courage to challenge',
			es: 'Coraje para desafiar',
			fr: 'Courage de défier',
			de: 'Mut zur Herausforderung',
			pt: 'Coragem para desafiar',
		},
	},
	{
		id: 'focus',
		romaji: 'Shūchū suru',
		texts: {
			ja: '集中する',
			en: 'Stay focused',
			es: 'Mantente enfocado',
			fr: 'Reste concentré',
			de: 'Bleib fokussiert',
			pt: 'Permaneça focado',
		},
	},
	{
		id: 'patience',
		romaji: 'Gaman suru',
		texts: {
			ja: '我慢する',
			en: 'Endure with patience',
			es: 'Perseverar con paciencia',
			fr: 'Endurer avec patience',
			de: 'Mit Geduld durchhalten',
			pt: 'Perseverar com paciência',
		},
	},
	{
		id: 'determination',
		romaji: 'Ketsui wo kimeru',
		texts: {
			ja: '決意を決める',
			en: 'Make your resolve',
			es: 'Determina tu voluntad',
			fr: 'Prends ta résolution',
			de: 'Fasse deinen Entschluss',
			pt: 'Faça sua determinação',
		},
	},
	{
		id: 'breakthrough',
		romaji: 'Toppa suru',
		texts: {
			ja: '突破する',
			en: 'Break through barriers',
			es: 'Rompe barreras',
			fr: 'Franchir les barrières',
			de: 'Durchbreche Barrieren',
			pt: 'Rompa barreiras',
		},
	},
	{
		id: 'transform',
		romaji: 'Henshin suru',
		texts: {
			ja: '変身する',
			en: 'Transform yourself',
			es: 'Transfórmate',
			fr: 'Transforme-toi',
			de: 'Verwandle dich',
			pt: 'Transforme-se',
		},
	},
	{
		id: 'progress',
		romaji: 'Shinpo suru',
		texts: {
			ja: '進歩する',
			en: 'Make progress',
			es: 'Avanza',
			fr: 'Progresse',
			de: 'Mache Fortschritte',
			pt: 'Faça progresso',
		},
	},
	{
		id: 'overcome',
		romaji: 'Norikoeru',
		texts: {
			ja: '乗り越える',
			en: 'Overcome obstacles',
			es: 'Supera obstáculos',
			fr: 'Surmonte les obstacles',
			de: 'Überwinde Hindernisse',
			pt: 'Supere obstáculos',
		},
	},
	{
		id: 'never-give-up',
		romaji: 'Akiramenai',
		texts: {
			ja: '諦めない',
			en: 'Never give up',
			es: 'Nunca te rindas',
			fr: "N'abandonne jamais",
			de: 'Gib niemals auf',
			pt: 'Nunca desista',
		},
	},
	{
		id: 'believe',
		romaji: 'Jibun wo shinjiru',
		texts: {
			ja: '自分を信じる',
			en: 'Believe in yourself',
			es: 'Cree en ti mismo',
			fr: 'Crois en toi',
			de: 'Glaube an dich',
			pt: 'Acredite em si mesmo',
		},
	},
	{
		id: 'effort',
		romaji: 'Doryoku suru',
		texts: {
			ja: '努力する',
			en: 'Put in effort',
			es: 'Esfuérzate',
			fr: 'Fais des efforts',
			de: 'Strenge dich an',
			pt: 'Faça esforço',
		},
	},
	{
		id: 'dedication',
		romaji: 'Kenshin suru',
		texts: {
			ja: '献身する',
			en: 'Dedicate yourself',
			es: 'Dedícate',
			fr: 'Dédie-toi',
			de: 'Widme dich',
			pt: 'Dedique-se',
		},
	},
	{
		id: 'pursue-dreams',
		romaji: 'Yume wo ou',
		texts: {
			ja: '夢を追う',
			en: 'Chase your dreams',
			es: 'Persigue tus sueños',
			fr: 'Poursuis tes rêves',
			de: 'Verfolge deine Träume',
			pt: 'Persiga seus sonhos',
		},
	},
	{
		id: 'take-action',
		romaji: 'Kōdō suru',
		texts: {
			ja: '行動する',
			en: 'Take action now',
			es: 'Actúa ahora',
			fr: 'Agis maintenant',
			de: 'Handle jetzt',
			pt: 'Aja agora',
		},
	},
	{
		id: 'persevere',
		romaji: 'Nintai suru',
		texts: {
			ja: '忍耐する',
			en: 'Persevere through hardship',
			es: 'Persevera ante las dificultades',
			fr: 'Persévère malgré les difficultés',
			de: 'Halte durch trotz Schwierigkeiten',
			pt: 'Persevere nas dificuldades',
		},
	},
	{
		id: 'seize-day',
		romaji: 'Kyō wo tsukamu',
		texts: {
			ja: '今日をつかむ',
			en: 'Seize the day',
			es: 'Aprovecha el día',
			fr: 'Saisis le jour',
			de: 'Nutze den Tag',
			pt: 'Aproveite o dia',
		},
	},
	{
		id: 'limitless',
		romaji: 'Mugen no kanōsei',
		texts: {
			ja: '無限の可能性',
			en: 'Limitless possibilities',
			es: 'Posibilidades infinitas',
			fr: 'Possibilités infinies',
			de: 'Unbegrenzte Möglichkeiten',
			pt: 'Possibilidades ilimitadas',
		},
	},
	{
		id: 'discipline',
		romaji: 'Jiritsu suru',
		texts: {
			ja: '自律する',
			en: 'Master self-discipline',
			es: 'Domina la autodisciplina',
			fr: "Maîtrise l'autodiscipline",
			de: 'Beherrsche Selbstdisziplin',
			pt: 'Domine a autodisciplina',
		},
	},
	{
		id: 'rise-above',
		romaji: 'Koete tatsu',
		texts: {
			ja: '超えて立つ',
			en: 'Rise above challenges',
			es: 'Elévate sobre los desafíos',
			fr: 'Élève-toi au-dessus des défis',
			de: 'Erhebe dich über Herausforderungen',
			pt: 'Eleve-se acima dos desafios',
		},
	},
	{
		id: 'win-day',
		romaji: 'Kyō wo katsu',
		texts: {
			ja: '今日を勝つ',
			en: 'Win the day',
			es: 'Gana el día',
			fr: 'Gagne la journée',
			de: 'Gewinne den Tag',
			pt: 'Vença o dia',
		},
	},
	{
		id: 'embrace-change',
		romaji: 'Henka wo ukeireru',
		texts: {
			ja: '変化を受け入れる',
			en: 'Embrace change',
			es: 'Acepta el cambio',
			fr: 'Accepte le changement',
			de: 'Nimm Veränderung an',
			pt: 'Abrace a mudança',
		},
	},
	{
		id: 'courage',
		romaji: 'Yūki wo motsu',
		texts: {
			ja: '勇気を持つ',
			en: 'Have courage',
			es: 'Ten coraje',
			fr: 'Aie du courage',
			de: 'Habe Mut',
			pt: 'Tenha coragem',
		},
	},
	{
		id: 'evolve',
		romaji: 'Shinka suru',
		texts: {
			ja: '進化する',
			en: 'Evolve continuously',
			es: 'Evoluciona continuamente',
			fr: 'Évolue continuellement',
			de: 'Entwickle dich stetig',
			pt: 'Evolua continuamente',
		},
	},
	{
		id: 'unstoppable',
		romaji: 'Tomerarenai',
		texts: {
			ja: '止められない',
			en: 'Be unstoppable',
			es: 'Sé imparable',
			fr: 'Sois inarrêtable',
			de: 'Sei unaufhaltsam',
			pt: 'Seja imparável',
		},
	},
	{
		id: 'create-future',
		romaji: 'Mirai wo tsukuru',
		texts: {
			ja: '未来を作る',
			en: 'Create your future',
			es: 'Crea tu futuro',
			fr: 'Crée ton avenir',
			de: 'Erschaffe deine Zukunft',
			pt: 'Crie seu futuro',
		},
	},
	{
		id: 'climb-mountain',
		romaji: 'Yama wo noboru',
		texts: {
			ja: '山を登る',
			en: 'Climb your mountain',
			es: 'Escala tu montaña',
			fr: 'Gravis ta montagne',
			de: 'Erklimme deinen Berg',
			pt: 'Escale sua montanha',
		},
	},
	{
		id: 'be-bold',
		romaji: 'Daitan ni naru',
		texts: {
			ja: '大胆になる',
			en: 'Be bold',
			es: 'Sé audaz',
			fr: 'Sois audacieux',
			de: 'Sei mutig',
			pt: 'Seja ousado',
		},
	},
	{
		id: 'ignite',
		romaji: 'Moeru',
		texts: {
			ja: '燃える',
			en: 'Ignite your passion',
			es: 'Enciende tu pasión',
			fr: 'Allume ta passion',
			de: 'Entfache deine Leidenschaft',
			pt: 'Acenda sua paixão',
		},
	},
	{
		id: 'find-way',
		romaji: 'Michi wo hiraku',
		texts: {
			ja: '道を開く',
			en: 'Find your way',
			es: 'Encuentra tu camino',
			fr: 'Trouve ton chemin',
			de: 'Finde deinen Weg',
			pt: 'Encontre seu caminho',
		},
	},
	{
		id: 'master-craft',
		romaji: 'Waza wo migaku',
		texts: {
			ja: '技を磨く',
			en: 'Master your craft',
			es: 'Domina tu oficio',
			fr: 'Maîtrise ton art',
			de: 'Beherrsche dein Handwerk',
			pt: 'Domine seu ofício',
		},
	},
	{
		id: 'small-steps',
		romaji: 'Chiisana ippo',
		texts: {
			ja: '小さな一歩',
			en: 'Small steps matter',
			es: 'Los pequeños pasos importan',
			fr: 'Les petits pas comptent',
			de: 'Kleine Schritte zählen',
			pt: 'Pequenos passos importam',
		},
	},
	{
		id: 'keep-going',
		romaji: 'Susumitsuzukeru',
		texts: {
			ja: '進み続ける',
			en: 'Keep going forward',
			es: 'Sigue adelante',
			fr: 'Continue à avancer',
			de: 'Geh weiter vorwärts',
			pt: 'Continue avançando',
		},
	},
	{
		id: 'unlock-potential',
		romaji: 'Kanōsei wo hiraku',
		texts: {
			ja: '可能性を開く',
			en: 'Unlock your potential',
			es: 'Desbloquea tu potencial',
			fr: 'Libère ton potentiel',
			de: 'Entfalte dein Potenzial',
			pt: 'Desbloqueie seu potencial',
		},
	},
	{
		id: 'stay-strong',
		romaji: 'Tsuyoku aru',
		texts: {
			ja: '強くある',
			en: 'Stay strong',
			es: 'Mantente fuerte',
			fr: 'Reste fort',
			de: 'Bleib stark',
			pt: 'Permaneça forte',
		},
	},
	{
		id: 'own-path',
		romaji: 'Jibun no michi',
		texts: {
			ja: '自分の道',
			en: 'Walk your own path',
			es: 'Camina tu propio sendero',
			fr: 'Marche sur ton propre chemin',
			de: 'Gehe deinen eigenen Weg',
			pt: 'Caminhe seu próprio caminho',
		},
	},
	{
		id: 'strive-excellence',
		romaji: 'Yūshū wo mezasu',
		texts: {
			ja: '優秀を目指す',
			en: 'Strive for excellence',
			es: 'Busca la excelencia',
			fr: "Vise l'excellence",
			de: 'Strebe nach Exzellenz',
			pt: 'Busque a excelência',
		},
	},
	{
		id: 'build-legacy',
		romaji: 'Isan wo kizuku',
		texts: {
			ja: '遺産を築く',
			en: 'Build your legacy',
			es: 'Construye tu legado',
			fr: 'Construis ton héritage',
			de: 'Baue dein Vermächtnis',
			pt: 'Construa seu legado',
		},
	},
	{
		id: 'exceed-limits',
		romaji: 'Genkai wo koeru',
		texts: {
			ja: '限界を超える',
			en: 'Exceed your limits',
			es: 'Supera tus límites',
			fr: 'Dépasse tes limites',
			de: 'Überschreite deine Grenzen',
			pt: 'Supere seus limites',
		},
	},
	{
		id: 'trust-process',
		romaji: 'Katei wo shinjiru',
		texts: {
			ja: '過程を信じる',
			en: 'Trust the process',
			es: 'Confía en el proceso',
			fr: 'Fais confiance au processus',
			de: 'Vertraue dem Prozess',
			pt: 'Confie no processo',
		},
	},
	{
		id: 'make-happen',
		romaji: 'Jitsugen suru',
		texts: {
			ja: '実現する',
			en: 'Make it happen',
			es: 'Hazlo realidad',
			fr: 'Fais-le arriver',
			de: 'Mach es möglich',
			pt: 'Faça acontecer',
		},
	},
	{
		id: 'forge-ahead',
		romaji: 'Zenshin suru',
		texts: {
			ja: '前進する',
			en: 'Forge ahead',
			es: 'Avanza con fuerza',
			fr: 'Avance avec force',
			de: 'Schmiede vorwärts',
			pt: 'Avance com força',
		},
	},
	{
		id: 'turn-around',
		romaji: 'Gyakuten suru',
		texts: {
			ja: '逆転する',
			en: 'Turn it around',
			es: 'Dale la vuelta',
			fr: 'Renverse la situation',
			de: 'Dreh es um',
			pt: 'Vire o jogo',
		},
	},
]

export const AFFIRMATIONS: Phrase[] = [
	{
		id: 'capable',
		romaji: 'Watashi wa dekiru',
		texts: {
			ja: '私はできる',
			en: 'I am capable',
			es: 'Soy capaz',
			fr: 'Je suis capable',
			de: 'Ich bin fähig',
			pt: 'Eu sou capaz',
		},
	},
	{
		id: 'enough',
		romaji: 'Watashi wa jūbun da',
		texts: {
			ja: '私は十分だ',
			en: 'I am enough',
			es: 'Soy suficiente',
			fr: 'Je suis suffisant',
			de: 'Ich bin genug',
			pt: 'Eu sou suficiente',
		},
	},
	{
		id: 'grateful',
		romaji: 'Kansha no kokoro',
		texts: {
			ja: '感謝の心',
			en: 'I am grateful',
			es: 'Estoy agradecido',
			fr: 'Je suis reconnaissant',
			de: 'Ich bin dankbar',
			pt: 'Eu sou grato',
		},
	},
	{
		id: 'peace',
		romaji: 'Kokoro ni heiwa',
		texts: {
			ja: '心に平和',
			en: 'Peace in my heart',
			es: 'Paz en mi corazón',
			fr: 'Paix dans mon cœur',
			de: 'Frieden in meinem Herzen',
			pt: 'Paz no meu coração',
		},
	},
	{
		id: 'strength-within',
		romaji: 'Uchi naru tsuyosa',
		texts: {
			ja: '内なる強さ',
			en: 'Strength lies within me',
			es: 'La fuerza está dentro de mí',
			fr: 'La force est en moi',
			de: 'Die Stärke liegt in mir',
			pt: 'A força está dentro de mim',
		},
	},
	{
		id: 'worthy',
		romaji: 'Watashi wa kachi ga aru',
		texts: {
			ja: '私は価値がある',
			en: 'I am worthy of love',
			es: 'Soy digno de amor',
			fr: "Je suis digne d'amour",
			de: 'Ich bin der Liebe würdig',
			pt: 'Eu sou digno de amor',
		},
	},
	{
		id: 'choose-joy',
		romaji: 'Kyō, yorokobi wo erabu',
		texts: {
			ja: '今日、喜びを選ぶ',
			en: 'Today I choose joy',
			es: 'Hoy elijo la alegría',
			fr: "Aujourd'hui je choisis la joie",
			de: 'Heute wähle ich Freude',
			pt: 'Hoje eu escolho a alegria',
		},
	},
	{
		id: 'trust-journey',
		romaji: 'Tabi wo shinjiru',
		texts: {
			ja: '旅を信じる',
			en: 'I trust my journey',
			es: 'Confío en mi camino',
			fr: 'Je fais confiance à mon chemin',
			de: 'Ich vertraue meinem Weg',
			pt: 'Eu confio na minha jornada',
		},
	},
	{
		id: 'loved',
		romaji: 'Watashi wa aisareteiru',
		texts: {
			ja: '私は愛されている',
			en: 'I am loved',
			es: 'Soy amado',
			fr: 'Je suis aimé',
			de: 'Ich bin geliebt',
			pt: 'Eu sou amado',
		},
	},
	{
		id: 'resilient',
		romaji: 'Kaifuku-ryoku ga aru',
		texts: {
			ja: '回復力がある',
			en: 'I am resilient',
			es: 'Soy resiliente',
			fr: 'Je suis résilient',
			de: 'Ich bin widerstandsfähig',
			pt: 'Eu sou resiliente',
		},
	},
	{
		id: 'confident',
		romaji: 'Jishin ga aru',
		texts: {
			ja: '自信がある',
			en: 'I am confident',
			es: 'Soy confiado',
			fr: 'Je suis confiant',
			de: 'Ich bin selbstbewusst',
			pt: 'Eu sou confiante',
		},
	},
	{
		id: 'abundance',
		romaji: 'Hōfu ni megamareteiru',
		texts: {
			ja: '豊富に恵まれている',
			en: 'I have abundance',
			es: 'Tengo abundancia',
			fr: "J'ai l'abondance",
			de: 'Ich habe Überfluss',
			pt: 'Eu tenho abundância',
		},
	},
	{
		id: 'calm',
		romaji: 'Odayaka de aru',
		texts: {
			ja: '穏やかである',
			en: 'I am calm and centered',
			es: 'Estoy calmado y centrado',
			fr: 'Je suis calme et centré',
			de: 'Ich bin ruhig und zentriert',
			pt: 'Eu estou calmo e centrado',
		},
	},
	{
		id: 'powerful',
		romaji: 'Chikara ga aru',
		texts: {
			ja: '力がある',
			en: 'I am powerful',
			es: 'Soy poderoso',
			fr: 'Je suis puissant',
			de: 'Ich bin mächtig',
			pt: 'Eu sou poderoso',
		},
	},
	{
		id: 'safe',
		romaji: 'Anzen de aru',
		texts: {
			ja: '安全である',
			en: 'I am safe and protected',
			es: 'Estoy seguro y protegido',
			fr: 'Je suis en sécurité et protégé',
			de: 'Ich bin sicher und geschützt',
			pt: 'Eu estou seguro e protegido',
		},
	},
	{
		id: 'creative',
		romaji: 'Sōzō-ryoku ga aru',
		texts: {
			ja: '創造力がある',
			en: 'I am creative',
			es: 'Soy creativo',
			fr: 'Je suis créatif',
			de: 'Ich bin kreativ',
			pt: 'Eu sou criativo',
		},
	},
	{
		id: 'grow',
		romaji: 'Seichō shiteiru',
		texts: {
			ja: '成長している',
			en: 'I am growing',
			es: 'Estoy creciendo',
			fr: 'Je grandis',
			de: 'Ich wachse',
			pt: 'Eu estou crescendo',
		},
	},
	{
		id: 'unique',
		romaji: 'Yuniiku de aru',
		texts: {
			ja: 'ユニークである',
			en: 'I am unique',
			es: 'Soy único',
			fr: 'Je suis unique',
			de: 'Ich bin einzigartig',
			pt: 'Eu sou único',
		},
	},
	{
		id: 'whole',
		romaji: 'Kanzen de aru',
		texts: {
			ja: '完全である',
			en: 'I am whole',
			es: 'Soy completo',
			fr: 'Je suis entier',
			de: 'Ich bin vollständig',
			pt: 'Eu sou completo',
		},
	},
	{
		id: 'forgive',
		romaji: 'Yurusu koto ga dekiru',
		texts: {
			ja: '許すことができる',
			en: 'I forgive myself',
			es: 'Me perdono',
			fr: 'Je me pardonne',
			de: 'Ich vergebe mir',
			pt: 'Eu me perdoo',
		},
	},
	{
		id: 'brave',
		romaji: 'Yūkan de aru',
		texts: {
			ja: '勇敢である',
			en: 'I am brave',
			es: 'Soy valiente',
			fr: 'Je suis courageux',
			de: 'Ich bin mutig',
			pt: 'Eu sou corajoso',
		},
	},
	{
		id: 'beautiful',
		romaji: 'Utsukushii',
		texts: {
			ja: '美しい',
			en: 'I am beautiful',
			es: 'Soy hermoso',
			fr: 'Je suis beau',
			de: 'Ich bin schön',
			pt: 'Eu sou bonito',
		},
	},
	{
		id: 'wise',
		romaji: 'Kashikoi',
		texts: {
			ja: '賢い',
			en: 'I am wise',
			es: 'Soy sabio',
			fr: 'Je suis sage',
			de: 'Ich bin weise',
			pt: 'Eu sou sábio',
		},
	},
	{
		id: 'shine',
		romaji: 'Kagayaiteiru',
		texts: {
			ja: '輝いている',
			en: 'I shine my light',
			es: 'Brillo con mi luz',
			fr: 'Je rayonne ma lumière',
			de: 'Ich strahle mein Licht',
			pt: 'Eu brilho minha luz',
		},
	},
	{
		id: 'deserve-success',
		romaji: 'Seikō ni fusawashii',
		texts: {
			ja: '成功にふさわしい',
			en: 'I deserve success',
			es: 'Merezco el éxito',
			fr: 'Je mérite le succès',
			de: 'Ich verdiene Erfolg',
			pt: 'Eu mereço sucesso',
		},
	},
	{
		id: 'happy',
		romaji: 'Shiawase de aru',
		texts: {
			ja: '幸せである',
			en: 'I am happy',
			es: 'Soy feliz',
			fr: 'Je suis heureux',
			de: 'Ich bin glücklich',
			pt: 'Eu sou feliz',
		},
	},
	{
		id: 'healthy',
		romaji: 'Kenkō de aru',
		texts: {
			ja: '健康である',
			en: 'I am healthy',
			es: 'Soy saludable',
			fr: 'Je suis en bonne santé',
			de: 'Ich bin gesund',
			pt: 'Eu sou saudável',
		},
	},
	{
		id: 'accepted',
		romaji: 'Ukeirerareteiru',
		texts: {
			ja: '受け入れられている',
			en: 'I am accepted',
			es: 'Soy aceptado',
			fr: 'Je suis accepté',
			de: 'Ich bin akzeptiert',
			pt: 'Eu sou aceito',
		},
	},
	{
		id: 'fearless',
		romaji: 'Osorenai',
		texts: {
			ja: '恐れない',
			en: 'I am fearless',
			es: 'No tengo miedo',
			fr: 'Je suis sans peur',
			de: 'Ich bin furchtlos',
			pt: 'Eu não tenho medo',
		},
	},
	{
		id: 'blessed',
		romaji: 'Megumi wo uketeiru',
		texts: {
			ja: '恵みを受けている',
			en: 'I am blessed',
			es: 'Soy bendecido',
			fr: 'Je suis béni',
			de: 'Ich bin gesegnet',
			pt: 'Eu sou abençoado',
		},
	},
	{
		id: 'free',
		romaji: 'Jiyū de aru',
		texts: {
			ja: '自由である',
			en: 'I am free',
			es: 'Soy libre',
			fr: 'Je suis libre',
			de: 'Ich bin frei',
			pt: 'Eu sou livre',
		},
	},
	{
		id: 'kind',
		romaji: 'Yasashii',
		texts: {
			ja: '優しい',
			en: 'I am kind',
			es: 'Soy amable',
			fr: 'Je suis gentil',
			de: 'Ich bin freundlich',
			pt: 'Eu sou gentil',
		},
	},
	{
		id: 'balanced',
		romaji: 'Baransu ga toreteru',
		texts: {
			ja: 'バランスが取れてる',
			en: 'I am balanced',
			es: 'Estoy equilibrado',
			fr: 'Je suis équilibré',
			de: 'Ich bin ausgeglichen',
			pt: 'Eu estou equilibrado',
		},
	},
	{
		id: 'radiant',
		romaji: 'Kagayakashii',
		texts: {
			ja: '輝かしい',
			en: 'I am radiant',
			es: 'Soy radiante',
			fr: 'Je suis rayonnant',
			de: 'Ich bin strahlend',
			pt: 'Eu sou radiante',
		},
	},
	{
		id: 'authentic',
		romaji: 'Honmono de aru',
		texts: {
			ja: '本物である',
			en: 'I am authentic',
			es: 'Soy auténtico',
			fr: 'Je suis authentique',
			de: 'Ich bin authentisch',
			pt: 'Eu sou autêntico',
		},
	},
	{
		id: 'compassionate',
		romaji: 'Jihi-bukai',
		texts: {
			ja: '慈悲深い',
			en: 'I am compassionate',
			es: 'Soy compasivo',
			fr: 'Je suis compatissant',
			de: 'Ich bin mitfühlend',
			pt: 'Eu sou compassivo',
		},
	},
	{
		id: 'hopeful',
		romaji: 'Kibō ni michiteiru',
		texts: {
			ja: '希望に満ちている',
			en: 'I am hopeful',
			es: 'Tengo esperanza',
			fr: "J'ai de l'espoir",
			de: 'Ich bin hoffnungsvoll',
			pt: 'Eu tenho esperança',
		},
	},
	{
		id: 'present',
		romaji: 'Ima ni iru',
		texts: {
			ja: '今にいる',
			en: 'I am present',
			es: 'Estoy presente',
			fr: 'Je suis présent',
			de: 'Ich bin gegenwärtig',
			pt: 'Eu estou presente',
		},
	},
	{
		id: 'worthy-rest',
		romaji: 'Yasumu kachi ga aru',
		texts: {
			ja: '休む価値がある',
			en: 'I deserve rest',
			es: 'Merezco descansar',
			fr: 'Je mérite du repos',
			de: 'Ich verdiene Ruhe',
			pt: 'Eu mereço descanso',
		},
	},
	{
		id: 'open',
		romaji: 'Kokoro ga hiraiteiru',
		texts: {
			ja: '心が開いている',
			en: 'My heart is open',
			es: 'Mi corazón está abierto',
			fr: 'Mon cœur est ouvert',
			de: 'Mein Herz ist offen',
			pt: 'Meu coração está aberto',
		},
	},
	{
		id: 'healed',
		romaji: 'Iyasareteiru',
		texts: {
			ja: '癒されている',
			en: 'I am healed',
			es: 'Estoy sanado',
			fr: 'Je suis guéri',
			de: 'Ich bin geheilt',
			pt: 'Eu estou curado',
		},
	},
	{
		id: 'intentional',
		romaji: 'Ito-teki de aru',
		texts: {
			ja: '意図的である',
			en: 'I am intentional',
			es: 'Soy intencional',
			fr: 'Je suis intentionnel',
			de: 'Ich bin absichtlich',
			pt: 'Eu sou intencional',
		},
	},
	{
		id: 'flourishing',
		romaji: 'Hanajō shiteiru',
		texts: {
			ja: '花盛りしている',
			en: 'I am flourishing',
			es: 'Estoy floreciendo',
			fr: 'Je prospère',
			de: 'Ich blühe auf',
			pt: 'Eu estou florescendo',
		},
	},
	{
		id: 'anchored',
		romaji: 'Shikkari shiteiru',
		texts: {
			ja: 'しっかりしている',
			en: 'I am anchored',
			es: 'Estoy anclado',
			fr: 'Je suis ancré',
			de: 'Ich bin verankert',
			pt: 'Eu estou ancorado',
		},
	},
	{
		id: 'gentle',
		romaji: 'Yasashiku aru',
		texts: {
			ja: '優しくある',
			en: 'I am gentle with myself',
			es: 'Soy gentil conmigo',
			fr: 'Je suis doux avec moi-même',
			de: 'Ich bin sanft zu mir',
			pt: 'Eu sou gentil comigo',
		},
	},
	{
		id: 'limitless-love',
		romaji: 'Mugen no ai',
		texts: {
			ja: '無限の愛',
			en: 'My love is limitless',
			es: 'Mi amor es ilimitado',
			fr: 'Mon amour est illimité',
			de: 'Meine Liebe ist grenzenlos',
			pt: 'Meu amor é ilimitado',
		},
	},
	{
		id: 'inspired',
		romaji: 'Insupaiya sareteru',
		texts: {
			ja: 'インスパイヤされてる',
			en: 'I am inspired',
			es: 'Estoy inspirado',
			fr: 'Je suis inspiré',
			de: 'Ich bin inspiriert',
			pt: 'Eu estou inspirado',
		},
	},
	{
		id: 'vibrant',
		romaji: 'Ikiki shiteiru',
		texts: {
			ja: '生き生きしている',
			en: 'I am vibrant',
			es: 'Soy vibrante',
			fr: 'Je suis vibrant',
			de: 'Ich bin lebendig',
			pt: 'Eu sou vibrante',
		},
	},
	{
		id: 'becoming',
		romaji: 'Natte iku',
		texts: {
			ja: 'なっていく',
			en: 'I am becoming',
			es: 'Estoy convirtiéndome',
			fr: 'Je deviens',
			de: 'Ich werde',
			pt: 'Eu estou me tornando',
		},
	},
]

export const HAIKUS: Phrase[] = [
	{
		id: 'frog',
		romaji: 'Furu ike ya\nKawazu tobikomu\nMizu no oto',
		texts: {
			ja: '古池や\n蛙飛び込む\n水の音',
			en: 'Old pond—\na frog jumps in,\nsound of water',
			es: 'Viejo estanque—\nuna rana salta,\nsonido del agua',
			fr: "Vieil étang—\nune grenouille plonge,\nbruit de l'eau",
			de: 'Alter Teich—\nein Frosch springt hinein,\nKlang des Wassers',
			pt: 'Velho lago—\num sapo salta,\nsom da água',
		},
	},
	{
		id: 'autumn',
		romaji: 'Aki fukaki\nTonari wa nani wo\nSuru hito zo',
		texts: {
			ja: '秋深き\n隣は何を\nする人ぞ',
			en: 'Deep autumn—\nmy neighbor,\nwhat does he do?',
			es: 'Otoño profundo—\nmi vecino,\n¿qué hace?',
			fr: 'Automne profond—\nmon voisin,\nque fait-il?',
			de: 'Tiefer Herbst—\nmein Nachbar,\nwas tut er?',
			pt: 'Outono profundo—\nmeu vizinho,\no que faz?',
		},
	},
	{
		id: 'spring',
		romaji: 'Haru no umi\nHinemosu notari\nNotari kana',
		texts: {
			ja: '春の海\nひねもすのたり\nのたりかな',
			en: 'Spring sea—\nall day long, gently\nrising and falling',
			es: 'Mar de primavera—\ntodo el día, suavemente\nsubiendo y bajando',
			fr: 'Mer de printemps—\ntoute la journée, doucement\nmontant et descendant',
			de: 'Frühlingsmeer—\nden ganzen Tag, sanft\nsteigend und fallend',
			pt: 'Mar de primavera—\no dia todo, suavemente\nsubindo e descendo',
		},
	},
	{
		id: 'cherry',
		romaji: 'Chiru sakura\nNokoru sakura mo\nChiru sakura',
		texts: {
			ja: '散る桜\n残る桜も\n散る桜',
			en: 'Falling cherry blossoms—\nthose remaining\nwill also fall',
			es: 'Flores de cerezo cayendo—\nlas que quedan\ntambién caerán',
			fr: 'Fleurs de cerisier tombant—\ncelles qui restent\ntomberont aussi',
			de: 'Fallende Kirschblüten—\ndie verbleibenden\nwerden auch fallen',
			pt: 'Flores de cerejeira caindo—\nas que restam\ntambém cairão',
		},
	},
	{
		id: 'moon',
		romaji: 'Meigetsu wo\nTotte kurero to\nNaku ko kana',
		texts: {
			ja: '名月を\n取ってくれろと\n泣く子かな',
			en: 'Harvest moon—\nthe child cries,\n"get it for me!"',
			es: 'Luna de cosecha—\nel niño llora,\n"¡tráemela!"',
			fr: 'Lune des moissons—\nl\'enfant pleure,\n"attrape-la moi!"',
			de: 'Erntemond—\ndas Kind weint,\n"hol ihn mir!"',
			pt: 'Lua de colheita—\na criança chora,\n"pegue para mim!"',
		},
	},
	{
		id: 'snow',
		romaji: 'Yuki fureba\nFuyugomori seyo to\nTozasu mon',
		texts: {
			ja: '雪降れば\n冬籠りせよと\n閉ざす門',
			en: 'When snow falls,\nthe gate closes—\ntime to stay inside',
			es: 'Cuando cae la nieve,\nla puerta se cierra—\nhora de quedarse dentro',
			fr: 'Quand la neige tombe,\nle portail se ferme—\ntemps de rester dedans',
			de: 'Wenn Schnee fällt,\nschließt das Tor—\nZeit drinnen zu bleiben',
			pt: 'Quando a neve cai,\no portão se fecha—\nhora de ficar dentro',
		},
	},
	{
		id: 'summer',
		romaji: 'Shizukasa ya\nIwa ni shimiiru\nSemi no koe',
		texts: {
			ja: '閑さや\n岩にしみ入る\n蝉の声',
			en: "Such stillness—\nthe cicada's cry\npierces the rocks",
			es: 'Tal quietud—\nel canto de la cigarra\npenetra las rocas',
			fr: 'Tel silence—\nle cri de la cigale\npénètre les rochers',
			de: 'Solche Stille—\nder Schrei der Zikade\ndurchdringt die Felsen',
			pt: 'Tal quietude—\no canto da cigarra\npenetra as rochas',
		},
	},
	{
		id: 'path',
		romaji: 'Kono michi ya\nYuku hito nashi ni\nAki no kure',
		texts: {
			ja: 'この道や\n行く人なしに\n秋の暮れ',
			en: 'This road—\nno one walks it,\nautumn dusk',
			es: 'Este camino—\nnadie lo recorre,\natardecer de otoño',
			fr: "Ce chemin—\npersonne ne le parcourt,\ncrépuscule d'automne",
			de: 'Dieser Weg—\nniemand geht ihn,\nHerbstdämmerung',
			pt: 'Este caminho—\nninguém o percorre,\nentardecer de outono',
		},
	},
	{
		id: 'morning-glory',
		romaji: 'Asagao ya\nTsurube torarete\nMoraimizu',
		texts: {
			ja: '朝顔や\n釣瓶とられて\nもらい水',
			en: 'Morning glory—\nthe well bucket entangled,\nI beg for water',
			es: 'Gloria de la mañana—\nel cubo del pozo enredado,\npido agua',
			fr: 'Gloire du matin—\nle seau du puits emmêlé,\nje demande de l\'eau',
			de: 'Morgenruhm—\nder Brunneneimer verheddert,\nich bitte um Wasser',
			pt: 'Glória da manhã—\no balde do poço emaranhado,\npeço água',
		},
	},
	{
		id: 'winter-solitude',
		romaji: 'Fuyu kodoku\nYo wa subete\nKōru yo',
		texts: {
			ja: '冬孤独\n世はすべて\n凍る夜',
			en: 'Winter solitude—\nin a world of one color,\nthe sound of wind',
			es: 'Soledad invernal—\nen un mundo de un color,\nel sonido del viento',
			fr: 'Solitude hivernale—\ndans un monde d\'une couleur,\nle son du vent',
			de: 'Wintereinsamkeit—\nin einer Welt einer Farbe,\nder Klang des Windes',
			pt: 'Solidão invernal—\nem um mundo de uma cor,\no som do vento',
		},
	},
	{
		id: 'butterfly',
		romaji: 'Chō no tobu\nBakari nonaka no\nHinata kana',
		texts: {
			ja: '蝶の飛ぶ\nばかり野中の\n日なたかな',
			en: 'Butterflies—\nonly they fly\nacross the sunny fields',
			es: 'Mariposas—\nsolo ellas vuelan\npor los campos soleados',
			fr: 'Papillons—\nseuls ils volent\nà travers les champs ensoleillés',
			de: 'Schmetterlinge—\nnur sie fliegen\nüber die sonnigen Felder',
			pt: 'Borboletas—\nsomente elas voam\npelos campos ensolarados',
		},
	},
	{
		id: 'first-snow',
		romaji: 'Hatsu yuki ya\nKaketa hashi no\nTawamuredo',
		texts: {
			ja: '初雪や\nかけた橋の\nたわむれど',
			en: 'First snow—\njust enough to bend\nthe bridge boards',
			es: 'Primera nevada—\njusto suficiente para doblar\nlas tablas del puente',
			fr: 'Première neige—\njuste assez pour courber\nles planches du pont',
			de: 'Erster Schnee—\ngerade genug zum Biegen\nder Brückenbretter',
			pt: 'Primeira neve—\napenas o suficiente para dobrar\nas tábuas da ponte',
		},
	},
	{
		id: 'temple-bell',
		romaji: 'Kane kiete\nHana no ka wa tsuku\nYūbe kana',
		texts: {
			ja: '鐘消えて\n花の香は撞く\n夕べかな',
			en: 'Temple bell dies—\nbut the blossom scent rings on\nevening shade',
			es: 'Campana del templo muere—\npero el aroma de las flores resuena\nsombra vespertina',
			fr: 'Cloche du temple meurt—\nmais le parfum des fleurs résonne\nombre du soir',
			de: 'Tempelglocke stirbt—\naber der Blütenduft klingt\nAbendschatten',
			pt: 'Sino do templo morre—\nmas o aroma das flores ressoa\nsombra da tarde',
		},
	},
	{
		id: 'spring-rain',
		romaji: 'Harusame ya\nMonogatari yuku\nMino to kasa',
		texts: {
			ja: '春雨や\n物語ゆく\n蓑と笠',
			en: 'Spring rain—\ntelling stories as they go,\nstraw coat and umbrella',
			es: 'Lluvia de primavera—\ncontando historias mientras van,\nabrigo de paja y paraguas',
			fr: 'Pluie de printemps—\nracontant des histoires en allant,\nmanteau de paille et parapluie',
			de: 'Frühlingsregen—\nGeschichten erzählend,\nStrohmantel und Schirm',
			pt: 'Chuva de primavera—\ncontando histórias enquanto vão,\ncasaco de palha e guarda-chuva',
		},
	},
	{
		id: 'plum-blossom',
		romaji: 'Ume ga ka ni\nNotto hi no deru\nYamaji kana',
		texts: {
			ja: '梅が香に\nのっと日の出る\n山路かな',
			en: 'Plum blossom scent—\nsuddenly the sun rises,\nmountain path',
			es: 'Aroma de flor de ciruelo—\nde repente sale el sol,\nsendero de montaña',
			fr: 'Parfum de fleur de prunier—\nsoudain le soleil se lève,\nsentier de montagne',
			de: 'Pflaumenblütenduft—\nplötzlich geht die Sonne auf,\nBergpfad',
			pt: 'Aroma de flor de ameixa—\nde repente o sol nasce,\ncaminho da montanha',
		},
	},
	{
		id: 'lightning',
		romaji: 'Inazuma ya\nYami no kata yuku\nGoi no koe',
		texts: {
			ja: '稲妻や\n闇の方ゆく\n五位の声',
			en: 'Lightning flash—\ninto darkness goes\nthe night heron\'s cry',
			es: 'Relámpago—\nhacia la oscuridad va\nel grito de la garza',
			fr: 'Éclair—\nvers l\'obscurité va\nle cri du héron',
			de: 'Blitzlicht—\nin die Dunkelheit geht\nder Schrei des Reihers',
			pt: 'Relâmpago—\npara a escuridão vai\no grito da garça',
		},
	},
	{
		id: 'summer-grass',
		romaji: 'Natsu kusa ya\nTsuwamonodomo ga\nYume no ato',
		texts: {
			ja: '夏草や\n兵どもが\n夢の跡',
			en: 'Summer grass—\nall that remains\nof warriors\' dreams',
			es: 'Hierba de verano—\ntodo lo que queda\nde los sueños de guerreros',
			fr: 'Herbe d\'été—\ntout ce qui reste\ndes rêves des guerriers',
			de: 'Sommergras—\nalles was bleibt\nvon Kriegerträumen',
			pt: 'Grama de verão—\ntudo o que resta\ndos sonhos de guerreiros',
		},
	},
	{
		id: 'new-year',
		romaji: 'Gantan ya\nOmoeba sabishi\nAki no kure',
		texts: {
			ja: '元旦や\n思えば淋しき\n秋の暮',
			en: 'New Year\'s Day—\nthinking back, how lonely\nautumn dusk was',
			es: 'Día de Año Nuevo—\npensando atrás, qué solitario\nfue el atardecer de otoño',
			fr: 'Jour de l\'An—\nrepensant, comme c\'était solitaire\nle crépuscule d\'automne',
			de: 'Neujahrstag—\nzurückdenkend, wie einsam\ndie Herbstdämmerung war',
			pt: 'Dia de Ano Novo—\npensando atrás, quão solitário\nfoi o entardecer de outono',
		},
	},
	{
		id: 'full-moon',
		romaji: 'Meigetsu ya\nIke wo megurite\nYo mo sugara',
		texts: {
			ja: '名月や\n池をめぐりて\n夜もすがら',
			en: 'Full moon—\nwalking around the pond\nall night long',
			es: 'Luna llena—\ncaminando alrededor del estanque\ntoda la noche',
			fr: 'Pleine lune—\nmarchant autour de l\'étang\ntoute la nuit',
			de: 'Vollmond—\num den Teich gehend\ndie ganze Nacht',
			pt: 'Lua cheia—\ncaminhando ao redor do lago\na noite toda',
		},
	},
	{
		id: 'dragonfly',
		romaji: 'Akatombo\nSuzushisa no iro\nMisete tobu',
		texts: {
			ja: '赤蜻蛉\n涼しさの色\n見せて飛ぶ',
			en: 'Red dragonfly—\nshowing the color\nof coolness',
			es: 'Libélula roja—\nmostrando el color\nde la frescura',
			fr: 'Libellule rouge—\nmontrant la couleur\nde la fraîcheur',
			de: 'Rote Libelle—\nzeigt die Farbe\nder Kühle',
			pt: 'Libélula vermelha—\nmostrando a cor\nda frescura',
		},
	},
	{
		id: 'evening-snow',
		romaji: 'Yūgure ya\nYuki furu yama wo\nMite aruku',
		texts: {
			ja: '夕暮れや\n雪降る山を\n見て歩く',
			en: 'Evening dusk—\nwatching snow fall\non the mountain',
			es: 'Atardecer—\nviendo caer la nieve\nen la montaña',
			fr: 'Crépuscule—\nregardant la neige tomber\nsur la montagne',
			de: 'Abenddämmerung—\nSchnee fallen sehen\nauf dem Berg',
			pt: 'Entardecer—\nvendo a neve cair\nna montanha',
		},
	},
	{
		id: 'autumn-wind',
		romaji: 'Akikaze ya\nKumo ni tsukarete\nNaku karasu',
		texts: {
			ja: '秋風や\n雲に疲れて\n鳴く烏',
			en: 'Autumn wind—\ntired by the clouds,\na crow cries',
			es: 'Viento de otoño—\ncansado por las nubes,\nun cuervo grita',
			fr: 'Vent d\'automne—\nfatigué par les nuages,\nun corbeau crie',
			de: 'Herbstwind—\nmüde von den Wolken,\nein Rabe schreit',
			pt: 'Vento de outono—\ncansado pelas nuvens,\num corvo grita',
		},
	},
	{
		id: 'winter-moon',
		romaji: 'Fuyu no tsuki\nKage mo samukere\nMizu no ue',
		texts: {
			ja: '冬の月\n影も寒けれ\n水の上',
			en: 'Winter moon—\neven its shadow\ncold on the water',
			es: 'Luna de invierno—\nincluso su sombra\nfría sobre el agua',
			fr: 'Lune d\'hiver—\nmême son ombre\nfroide sur l\'eau',
			de: 'Wintermond—\nsogar sein Schatten\nkalt auf dem Wasser',
			pt: 'Lua de inverno—\naté sua sombra\nfria sobre a água',
		},
	},
	{
		id: 'peony',
		romaji: 'Botan chitte\nUchi kasanarinu\nNisan-pen',
		texts: {
			ja: '牡丹散りて\n打ち重なりぬ\n二三片',
			en: 'Peony petals fall—\npiling up, two or three\npieces together',
			es: 'Pétalos de peonía caen—\napilándose, dos o tres\npiezas juntas',
			fr: 'Pétales de pivoine tombent—\ns\'empilant, deux ou trois\nmorceaux ensemble',
			de: 'Pfingstrosenblätter fallen—\nsich häufend, zwei oder drei\nStücke zusammen',
			pt: 'Pétalas de peônia caem—\nempilhando, duas ou três\npeças juntas',
		},
	},
	{
		id: 'summer-moon',
		romaji: 'Natsu no tsuki\nGoten ni michiru\nShio no oto',
		texts: {
			ja: '夏の月\n御殿に満ちる\n潮の音',
			en: 'Summer moon—\nfilling the palace,\nsound of the tide',
			es: 'Luna de verano—\nllenando el palacio,\nsonido de la marea',
			fr: 'Lune d\'été—\nremplissant le palais,\nbruit de la marée',
			de: 'Sommermond—\nfüllt den Palast,\nKlang der Gezeiten',
			pt: 'Lua de verão—\nenchendo o palácio,\nsom da maré',
		},
	},
	{
		id: 'spring-night',
		romaji: 'Haru no yo ya\nKomori no sumika\nSumu tsuki',
		texts: {
			ja: '春の夜や\n籠り の住処\n住む月',
			en: 'Spring night—\nin the hermit\'s dwelling,\nlives the moon',
			es: 'Noche de primavera—\nen la morada del ermitaño,\nvive la luna',
			fr: 'Nuit de printemps—\ndans la demeure de l\'ermite,\nvit la lune',
			de: 'Frühlingsnacht—\nin der Behausung des Einsiedlers,\nlebt der Mond',
			pt: 'Noite de primavera—\nna morada do eremita,\nvive a lua',
		},
	},
	{
		id: 'dewdrop',
		romaji: 'Tsuyu no yo wa\nTsuyu no yo nagara\nSari nagara',
		texts: {
			ja: '露の世は\n露の世ながら\nさりながら',
			en: 'This dewdrop world—\na dewdrop world it is,\nand yet, and yet...',
			es: 'Este mundo de rocío—\nun mundo de rocío es,\ny sin embargo, y sin embargo...',
			fr: 'Ce monde de rosée—\nun monde de rosée c\'est,\net pourtant, et pourtant...',
			de: 'Diese Tautropfenwelt—\neine Tautropfenwelt ist es,\nund doch, und doch...',
			pt: 'Este mundo de orvalho—\num mundo de orvalho é,\ne ainda assim, e ainda assim...',
		},
	},
	{
		id: 'willow',
		romaji: 'Yanagi chiri\nShimizu kare ishi\nTokorodokoro',
		texts: {
			ja: '柳散り\n清水涸れ石\nところどころ',
			en: 'Willow leaves fall—\nthe spring runs dry,\nstones here and there',
			es: 'Hojas de sauce caen—\nla primavera se seca,\npiedras aquí y allá',
			fr: 'Feuilles de saule tombent—\nla source se tarit,\npierres ici et là',
			de: 'Weidenblätter fallen—\ndie Quelle trocknet,\nSteine hier und da',
			pt: 'Folhas de salgueiro caem—\na nascente seca,\npedras aqui e ali',
		},
	},
	{
		id: 'bamboo-shoot',
		romaji: 'Takenoko ya\nKodomo no toki no\nKusa no io',
		texts: {
			ja: '竹の子や\n子供の時の\n草の庵',
			en: 'Bamboo shoots—\nchildhood memories\nof a grass hut',
			es: 'Brotes de bambú—\nrecuerdos de infancia\nde una choza de hierba',
			fr: 'Pousses de bambou—\nsouvenirs d\'enfance\nd\'une hutte d\'herbe',
			de: 'Bambussprossen—\nKindheitserinnerungen\nan eine Grashütte',
			pt: 'Brotos de bambu—\nmemórias de infância\nde uma cabana de grama',
		},
	},
	{
		id: 'iris',
		romaji: 'Kakitsubata\nKatarui yuku ka\nNami no ue',
		texts: {
			ja: 'かきつばた\n語らい行くか\n波の上',
			en: 'Iris flowers—\ntalking as they go\nover the waves',
			es: 'Flores de iris—\nhablando mientras van\nsobre las olas',
			fr: 'Fleurs d\'iris—\nparlant en allant\nsur les vagues',
			de: 'Irisblüten—\nredend wie sie gehen\nüber die Wellen',
			pt: 'Flores de íris—\nconversando enquanto vão\nsobre as ondas',
		},
	},
	{
		id: 'winter-wind',
		romaji: 'Kogarashi ya\nTake ni kakurete\nShizumari nu',
		texts: {
			ja: '木枯しや\n竹にかくれて\n静まりぬ',
			en: 'Winter wind—\nhiding in bamboo,\nit quiets down',
			es: 'Viento invernal—\nescondiéndose en el bambú,\nse calma',
			fr: 'Vent d\'hiver—\nse cachant dans le bambou,\nil se calme',
			de: 'Winterwind—\nverborgen im Bambus,\nwird er ruhig',
			pt: 'Vento de inverno—\nescondendo-se no bambu,\nacalma-se',
		},
	},
	{
		id: 'hydrangea',
		romaji: 'Ajisai ya\nShiro yori shiroki\nShiro mo ari',
		texts: {
			ja: '紫陽花や\n白より白き\n白もあり',
			en: 'Hydrangeas—\nwhiter than white,\nsome whites exist',
			es: 'Hortensias—\nmás blanco que blanco,\nalgunos blancos existen',
			fr: 'Hortensias—\nplus blanc que blanc,\ncertains blancs existent',
			de: 'Hortensien—\nweißer als weiß,\neinige Weiße existieren',
			pt: 'Hortênsias—\nmais branco que branco,\nalguns brancos existem',
		},
	},
	{
		id: 'mountain-path',
		romaji: 'Yama-michi ya\nNani yara yukashi\nSumire-gusa',
		texts: {
			ja: '山道や\n何やらゆかし\n菫草',
			en: 'Mountain path—\nsomething about it,\nviolets',
			es: 'Sendero de montaña—\nalgo en él,\nvioletas',
			fr: 'Sentier de montagne—\nquelque chose à propos,\nviolettes',
			de: 'Bergpfad—\netwas daran,\nVeilchen',
			pt: 'Caminho da montanha—\nalgo nele,\nvioletas',
		},
	},
	{
		id: 'nightingale',
		romaji: 'Uguisu ya\nYanagi no ushiro\nYabu no mae',
		texts: {
			ja: '鶯や\n柳のうしろ\n藪の前',
			en: 'Nightingale—\nbehind the willow,\nbefore the thicket',
			es: 'Ruiseñor—\ndetrás del sauce,\nantes del matorral',
			fr: 'Rossignol—\nderrière le saule,\navant le fourré',
			de: 'Nachtigall—\nhinter der Weide,\nvor dem Dickicht',
			pt: 'Rouxinol—\natrás do salgueiro,\nantes do matagal',
		},
	},
	{
		id: 'stars',
		romaji: 'Hoshi no naka\nKoori no naka ni\nNaku karasu',
		texts: {
			ja: '星の中\n氷の中に\n鳴く烏',
			en: 'Among the stars—\ninside the ice,\na crow cries',
			es: 'Entre las estrellas—\ndentro del hielo,\nun cuervo grita',
			fr: 'Parmi les étoiles—\nà l\'intérieur de la glace,\nun corbeau crie',
			de: 'Unter den Sternen—\nim Eis drinnen,\nein Rabe schreit',
			pt: 'Entre as estrelas—\ndentro do gelo,\num corvo grita',
		},
	},
	{
		id: 'fog',
		romaji: 'Kiri harau\nTe mo arubeshi ni\nAki no kure',
		texts: {
			ja: '霧晴らう\n手もあるべしに\n秋の暮',
			en: 'Clearing the mist—\nthere must be a way,\nautumn dusk',
			es: 'Despejando la niebla—\ndebe haber un camino,\natardecer de otoño',
			fr: 'Dissipant le brouillard—\nil doit y avoir un moyen,\ncrépuscule d\'automne',
			de: 'Den Nebel lichtend—\nes muss einen Weg geben,\nHerbstdämmerung',
			pt: 'Limpando a névoa—\ndeve haver um caminho,\nentardecer de outono',
		},
	},
	{
		id: 'camellia',
		romaji: 'Tsubaki ochite\nKinō no ame wo\nKoboshikeri',
		texts: {
			ja: '椿落ちて\n昨日の雨を\nこぼしけり',
			en: 'Camellia falls—\nspilling yesterday\'s\nrain',
			es: 'Camelia cae—\nderramando la lluvia\nde ayer',
			fr: 'Camélia tombe—\nrenversant la pluie\nd\'hier',
			de: 'Kamelie fällt—\nverschüttet den Regen\nvon gestern',
			pt: 'Camélia cai—\nderramando a chuva\nde ontem',
		},
	},
	{
		id: 'clouds',
		romaji: 'Kumo no mine\nIkutsu kuzurete\nTsuki no kage',
		texts: {
			ja: '雲の峰\nいくつ崩れて\n月の影',
			en: 'Cloud peaks—\nhow many crumble\ninto moonlight',
			es: 'Picos de nubes—\ncuántos se desmoronan\nen luz de luna',
			fr: 'Pics de nuages—\ncombien s\'effondrent\ndans le clair de lune',
			de: 'Wolkengipfel—\nwie viele zerbröckeln\nins Mondlicht',
			pt: 'Picos de nuvens—\nquantos desmoronam\nna luz do luar',
		},
	},
	{
		id: 'kite',
		romaji: 'Tako agete\nSora wo shihai no\nKodomo kana',
		texts: {
			ja: '凧あげて\n空を支配の\n子供かな',
			en: 'Flying a kite—\nthe child commands\nthe sky',
			es: 'Volando una cometa—\nel niño comanda\nel cielo',
			fr: 'Faisant voler un cerf-volant—\nl\'enfant commande\nle ciel',
			de: 'Einen Drachen steigen—\ndas Kind beherrscht\nden Himmel',
			pt: 'Soltando uma pipa—\na criança comanda\no céu',
		},
	},
	{
		id: 'persimmon',
		romaji: 'Kaki kueba\nKane ga naru nari\nHōryūji',
		texts: {
			ja: '柿くえば\n鐘が鳴るなり\n法隆寺',
			en: 'Eating a persimmon—\nthe temple bell rings,\nHōryūji',
			es: 'Comiendo un caqui—\nla campana del templo suena,\nHōryūji',
			fr: 'Mangeant un kaki—\nla cloche du temple sonne,\nHōryūji',
			de: 'Eine Kaki essend—\ndie Tempelglocke läutet,\nHōryūji',
			pt: 'Comendo um caqui—\no sino do templo toca,\nHōryūji',
		},
	},
	{
		id: 'lotus',
		romaji: 'Hasu no ha ni\nTamaru mizu sae\nKiyoki kana',
		texts: {
			ja: '蓮の葉に\n溜まる水さえ\n清きかな',
			en: 'On lotus leaves—\neven the gathered water\nis pure',
			es: 'En hojas de loto—\nincluso el agua acumulada\nes pura',
			fr: 'Sur les feuilles de lotus—\nmême l\'eau accumulée\nest pure',
			de: 'Auf Lotusblättern—\nsogar das gesammelte Wasser\nist rein',
			pt: 'Em folhas de lótus—\naté a água acumulada\né pura',
		},
	},
	{
		id: 'sparrow',
		romaji: 'Suzume no ko\nSoko noke soko noke\nOuma ga tōru',
		texts: {
			ja: '雀の子\nそこのけそこのけ\nお馬が通る',
			en: 'Little sparrow—\nmove aside, move aside,\nthe horse is coming',
			es: 'Pequeño gorrión—\napártate, apártate,\nel caballo viene',
			fr: 'Petit moineau—\nécarte-toi, écarte-toi,\nle cheval arrive',
			de: 'Kleiner Spatz—\ngeh beiseite, geh beiseite,\ndas Pferd kommt',
			pt: 'Pequeno pardal—\nsaia, saia,\no cavalo está vindo',
		},
	},
	{
		id: 'pine',
		romaji: 'Matsu no oto\nTōku kikoyuru\nAki no kure',
		texts: {
			ja: '松の音\n遠く聞こゆる\n秋の暮',
			en: 'Pine tree sound—\nheard from afar,\nautumn evening',
			es: 'Sonido de pino—\nescuchado desde lejos,\ntarde de otoño',
			fr: 'Son du pin—\nentendu de loin,\nsoir d\'automne',
			de: 'Kiefernklang—\nvon fern gehört,\nHerbstabend',
			pt: 'Som de pinheiro—\nouvido ao longe,\ntarde de outono',
		},
	},
	{
		id: 'firefly',
		romaji: 'Hotaru kite\nOi no ue naru\nTsukiyo kana',
		texts: {
			ja: '蛍来て\n笈の上なる\n月夜かな',
			en: 'Firefly comes—\non top of my bag,\nmoonlit night',
			es: 'Luciérnaga viene—\nencima de mi bolsa,\nnoche de luna',
			fr: 'Luciole vient—\nsur mon sac,\nnuit de lune',
			de: 'Glühwürmchen kommt—\nauf meiner Tasche,\nMondnacht',
			pt: 'Vaga-lume vem—\nem cima da minha bolsa,\nnoite de luar',
		},
	},
	{
		id: 'wheat',
		romaji: 'Mugi no ho wo\nChikara ni tsumamu\nWakare kana',
		texts: {
			ja: '麦の穂を\n力につまむ\n別れかな',
			en: 'Wheat stalks—\ngripping them for strength,\nfarewell',
			es: 'Tallos de trigo—\nagarrándolos con fuerza,\ndespedida',
			fr: 'Tiges de blé—\nles serrant pour la force,\nadieu',
			de: 'Weizenhalme—\nsie kraftvoll greifend,\nAbschied',
			pt: 'Hastes de trigo—\nagarrando-as com força,\ndespedida',
		},
	},
	{
		id: 'ivy',
		romaji: 'Tsuta kaete\nNochi wa sakura no\nKi to zo naru',
		texts: {
			ja: '蔦替えて\n後は桜の\n木とぞなる',
			en: 'Ivy changes—\nafterward it becomes\na cherry tree',
			es: 'La hiedra cambia—\ndespués se convierte\nen cerezo',
			fr: 'Le lierre change—\naprès il devient\nun cerisier',
			de: 'Efeu wechselt—\ndanach wird es\nein Kirschbaum',
			pt: 'A hera muda—\ndepois torna-se\numa cerejeira',
		},
	},
	{
		id: 'twilight',
		romaji: 'Tasogare ya\nAme furu oto no\nYamadori',
		texts: {
			ja: '黄昏や\n雨降る音の\n山鳥',
			en: 'Twilight—\nthe sound of rain,\nmountain bird',
			es: 'Crepúsculo—\nel sonido de la lluvia,\npájaro de montaña',
			fr: 'Crépuscule—\nle son de la pluie,\noiseau de montagne',
			de: 'Dämmerung—\nder Klang des Regens,\nBergvogel',
			pt: 'Crepúsculo—\no som da chuva,\npássaro da montanha',
		},
	},
	{
		id: 'dawn',
		romaji: 'Akebono ya\nShira uo shiroki\nKoto issun',
		texts: {
			ja: '曙や\n白魚白き\nこと一寸',
			en: 'Dawn—\nthe whitebait,\none inch of whiteness',
			es: 'Amanecer—\nel chanquete,\nuna pulgada de blancura',
			fr: 'Aube—\nle blanchaille,\nun pouce de blancheur',
			de: 'Morgengrauen—\nder Weißfisch,\nein Zoll Weiße',
			pt: 'Amanhecer—\no peixe-branco,\numa polegada de brancura',
		},
	},
	{
		id: 'winter-tree',
		romaji: 'Fuyu kodachi\nTsuki ga ki ni sumu\nYō mo nashi',
		texts: {
			ja: '冬木立\n月が木に住む\nようもなし',
			en: 'Winter trees—\nthe moon doesn\'t seem\nto live in them',
			es: 'Árboles de invierno—\nla luna no parece\nvivir en ellos',
			fr: 'Arbres d\'hiver—\nla lune ne semble pas\nvivre en eux',
			de: 'Winterbäume—\nder Mond scheint nicht\nin ihnen zu leben',
			pt: 'Árvores de inverno—\na lua não parece\nviver nelas',
		},
	},
	{
		id: 'rain-crow',
		romaji: 'Ame karasu\nNaku ne mo kurashi\nMori no oku',
		texts: {
			ja: '雨烏\n鳴く音も暗し\n森の奥',
			en: 'Rain crow—\nits cry also dark,\ndeep in the forest',
			es: 'Cuervo de lluvia—\nsu grito también oscuro,\nprofundo en el bosque',
			fr: 'Corbeau de pluie—\nson cri aussi sombre,\nau fond de la forêt',
			de: 'Regenrabe—\nsein Schrei auch dunkel,\ntief im Wald',
			pt: 'Corvo de chuva—\nseu grito também escuro,\nprofundo na floresta',
		},
	},
]

export const WORDS: Phrase[] = [
	{
		id: 'komorebi',
		romaji: 'Komorebi',
		texts: {
			ja: '木漏れ日',
			en: 'Sunlight filtering through leaves',
			es: 'Luz del sol filtrándose entre hojas',
			fr: 'Lumière du soleil à travers les feuilles',
			de: 'Sonnenlicht durch Blätter',
			pt: 'Luz do sol através das folhas',
		},
	},
	{
		id: 'wabisabi',
		romaji: 'Wabi-sabi',
		texts: {
			ja: '侘寂',
			en: 'Beauty in imperfection',
			es: 'Belleza en la imperfección',
			fr: "Beauté dans l'imperfection",
			de: 'Schönheit in der Unvollkommenheit',
			pt: 'Beleza na imperfeição',
		},
	},
	{
		id: 'ikigai',
		romaji: 'Ikigai',
		texts: {
			ja: '生きがい',
			en: 'Reason for being',
			es: 'Razón de ser',
			fr: "Raison d'être",
			de: 'Lebenssinn',
			pt: 'Razão de viver',
		},
	},
	{
		id: 'kintsugi',
		romaji: 'Kintsugi',
		texts: {
			ja: '金継ぎ',
			en: 'Golden repair — embracing flaws',
			es: 'Reparación dorada — abrazar defectos',
			fr: 'Réparation dorée — embrasser les défauts',
			de: 'Goldene Reparatur — Fehler annehmen',
			pt: 'Reparo dourado — abraçar falhas',
		},
	},
	{
		id: 'shinrinyoku',
		romaji: 'Shinrin-yoku',
		texts: {
			ja: '森林浴',
			en: 'Forest bathing — nature immersion',
			es: 'Baño de bosque — inmersión en la naturaleza',
			fr: 'Bain de forêt — immersion dans la nature',
			de: 'Waldbaden — Eintauchen in die Natur',
			pt: 'Banho de floresta — imersão na natureza',
		},
	},
	{
		id: 'mono-no-aware',
		romaji: 'Mono no aware',
		texts: {
			ja: '物の哀れ',
			en: 'Bittersweet awareness of impermanence',
			es: 'Conciencia agridulce de lo efímero',
			fr: "Conscience douce-amère de l'impermanence",
			de: 'Bittersüßes Bewusstsein der Vergänglichkeit',
			pt: 'Consciência agridoce da impermanência',
		},
	},
	{
		id: 'musubi',
		romaji: 'Musubi',
		texts: {
			ja: '結び',
			en: 'Connection — the energy that binds',
			es: 'Conexión — la energía que une',
			fr: "Connexion — l'énergie qui lie",
			de: 'Verbindung — die Energie, die bindet',
			pt: 'Conexão — a energia que une',
		},
	},
	{
		id: 'yugen',
		romaji: 'Yūgen',
		texts: {
			ja: '幽玄',
			en: 'Profound, mysterious beauty',
			es: 'Belleza profunda y misteriosa',
			fr: 'Beauté profonde et mystérieuse',
			de: 'Tiefe, geheimnisvolle Schönheit',
			pt: 'Beleza profunda e misteriosa',
		},
	},
	{
		id: 'natsukashii',
		romaji: 'Natsukashii',
		texts: {
			ja: '懐かしい',
			en: 'Nostalgic longing for the past',
			es: 'Nostalgia por el pasado',
			fr: 'Nostalgie du passé',
			de: 'Sehnsucht nach der Vergangenheit',
			pt: 'Saudade do passado',
		},
	},
	{
		id: 'shoganai',
		romaji: 'Shōganai',
		texts: {
			ja: 'しょうがない',
			en: "It can't be helped — acceptance",
			es: 'No se puede evitar — aceptación',
			fr: "On n'y peut rien — acceptation",
			de: 'Es lässt sich nicht ändern — Akzeptanz',
			pt: 'Não tem jeito — aceitação',
		},
	},
	{
		id: 'tsundoku',
		romaji: 'Tsundoku',
		texts: {
			ja: '積読',
			en: 'Buying books and not reading them',
			es: 'Comprar libros sin leerlos',
			fr: 'Acheter des livres sans les lire',
			de: 'Bücher kaufen und nicht lesen',
			pt: 'Comprar livros sem lê-los',
		},
	},
	{
		id: 'karoshi',
		romaji: 'Karōshi',
		texts: {
			ja: '過労死',
			en: 'Death from overwork',
			es: 'Muerte por exceso de trabajo',
			fr: "Mort par surmenage",
			de: 'Tod durch Überarbeitung',
			pt: 'Morte por excesso de trabalho',
		},
	},
	{
		id: 'fuubutsushi',
		romaji: 'Fūbutsushi',
		texts: {
			ja: '風物詩',
			en: 'Seasonal tradition',
			es: 'Tradición estacional',
			fr: 'Tradition saisonnière',
			de: 'Saisonale Tradition',
			pt: 'Tradição sazonal',
		},
	},
	{
		id: 'aware',
		romaji: 'Aware',
		texts: {
			ja: 'あわれ',
			en: 'Poignant, touching beauty',
			es: 'Belleza conmovedora',
			fr: 'Beauté poignante',
			de: 'Ergreifende Schönheit',
			pt: 'Beleza comovente',
		},
	},
	{
		id: 'majime',
		romaji: 'Majime',
		texts: {
			ja: '真面目',
			en: 'Earnest, serious-minded',
			es: 'Serio, sincero',
			fr: 'Sérieux, sincère',
			de: 'Ernsthaft, gewissenhaft',
			pt: 'Sério, sincero',
		},
	},
	{
		id: 'omotenashi',
		romaji: 'Omotenashi',
		texts: {
			ja: 'おもてなし',
			en: 'Wholehearted hospitality',
			es: 'Hospitalidad sincera',
			fr: 'Hospitalité sincère',
			de: 'Aufrichtige Gastfreundschaft',
			pt: 'Hospitalidade sincera',
		},
	},
	{
		id: 'kodawari',
		romaji: 'Kodawari',
		texts: {
			ja: 'こだわり',
			en: 'Relentless pursuit of perfection',
			es: 'Búsqueda incansable de la perfección',
			fr: 'Quête incessante de la perfection',
			de: 'Unerbittliches Streben nach Perfektion',
			pt: 'Busca implacável da perfeição',
		},
	},
	{
		id: 'shouganai',
		romaji: 'Shikata ga nai',
		texts: {
			ja: '仕方がない',
			en: "It cannot be helped",
			es: 'No se puede hacer nada',
			fr: 'On ne peut rien y faire',
			de: 'Es kann nicht geholfen werden',
			pt: 'Não há o que fazer',
		},
	},
	{
		id: 'meiwaku',
		romaji: 'Meiwaku',
		texts: {
			ja: '迷惑',
			en: 'Causing trouble for others',
			es: 'Causar molestias a otros',
			fr: 'Causer des ennuis aux autres',
			de: 'Anderen Ärger bereiten',
			pt: 'Causar incômodo aos outros',
		},
	},
	{
		id: 'ganbatte',
		romaji: 'Ganbatte',
		texts: {
			ja: '頑張って',
			en: 'Do your best, persevere',
			es: 'Haz tu mejor esfuerzo',
			fr: 'Fais de ton mieux',
			de: 'Gib dein Bestes',
			pt: 'Faça o seu melhor',
		},
	},
	{
		id: 'boketto',
		romaji: 'Boketto',
		texts: {
			ja: 'ぼけっと',
			en: 'Gazing vacantly into distance',
			es: 'Mirar vacuamente a la distancia',
			fr: 'Regarder dans le vide',
			de: 'Leer in die Ferne starren',
			pt: 'Olhar vagamente para a distância',
		},
	},
	{
		id: 'yoroshiku',
		romaji: 'Yoroshiku',
		texts: {
			ja: 'よろしく',
			en: 'Please treat me favorably',
			es: 'Por favor, trátame bien',
			fr: 'Traite-moi favorablement',
			de: 'Bitte behandle mich gut',
			pt: 'Por favor, me trate bem',
		},
	},
	{
		id: 'kaizen',
		romaji: 'Kaizen',
		texts: {
			ja: '改善',
			en: 'Continuous improvement',
			es: 'Mejora continua',
			fr: 'Amélioration continue',
			de: 'Kontinuierliche Verbesserung',
			pt: 'Melhoria contínua',
		},
	},
	{
		id: 'mottainai',
		romaji: 'Mottainai',
		texts: {
			ja: 'もったいない',
			en: 'Waste nothing, respect resources',
			es: 'No desperdiciar, respetar recursos',
			fr: 'Ne rien gaspiller, respecter les ressources',
			de: 'Nichts verschwenden, Ressourcen respektieren',
			pt: 'Não desperdiçar, respeitar recursos',
		},
	},
	{
		id: 'tsuyoku',
		romaji: 'Tsuyoku',
		texts: {
			ja: '強く',
			en: 'Strongly, with power',
			es: 'Fuertemente, con poder',
			fr: 'Fortement, avec puissance',
			de: 'Stark, mit Kraft',
			pt: 'Fortemente, com poder',
		},
	},
	{
		id: 'hansei',
		romaji: 'Hansei',
		texts: {
			ja: '反省',
			en: 'Self-reflection, introspection',
			es: 'Autorreflexión, introspección',
			fr: 'Auto-réflexion, introspection',
			de: 'Selbstreflexion, Innenschau',
			pt: 'Autorreflexão, introspecção',
		},
	},
	{
		id: 'genki',
		romaji: 'Genki',
		texts: {
			ja: '元気',
			en: 'Energetic, healthy, spirited',
			es: 'Enérgico, saludable, animado',
			fr: 'Énergique, sain, plein d\'entrain',
			de: 'Energisch, gesund, lebhaft',
			pt: 'Enérgico, saudável, animado',
		},
	},
	{
		id: 'otsukare',
		romaji: 'Otsukaresama',
		texts: {
			ja: 'お疲れ様',
			en: 'Thank you for your hard work',
			es: 'Gracias por tu duro trabajo',
			fr: 'Merci pour ton travail',
			de: 'Danke für deine harte Arbeit',
			pt: 'Obrigado pelo seu trabalho',
		},
	},
	{
		id: 'shoubu',
		romaji: 'Shōbu',
		texts: {
			ja: '勝負',
			en: 'Match, showdown, challenge',
			es: 'Partido, confrontación, desafío',
			fr: 'Match, confrontation, défi',
			de: 'Kampf, Wettkampf, Herausforderung',
			pt: 'Partida, confronto, desafio',
		},
	},
	{
		id: 'enryo',
		romaji: 'Enryo',
		texts: {
			ja: '遠慮',
			en: 'Restraint, hesitation, reserve',
			es: 'Reserva, vacilación, discreción',
			fr: 'Retenue, hésitation, réserve',
			de: 'Zurückhaltung, Zögern, Reserve',
			pt: 'Reserva, hesitação, contenção',
		},
	},
	{
		id: 'kogarashi',
		romaji: 'Kogarashi',
		texts: {
			ja: '木枯らし',
			en: 'Cold wintry wind',
			es: 'Viento frío invernal',
			fr: 'Vent froid hivernal',
			de: 'Kalter Winterwind',
			pt: 'Vento frio de inverno',
		},
	},
	{
		id: 'ukiyo',
		romaji: 'Ukiyo',
		texts: {
			ja: '浮世',
			en: 'The floating world',
			es: 'El mundo flotante',
			fr: 'Le monde flottant',
			de: 'Die fließende Welt',
			pt: 'O mundo flutuante',
		},
	},
	{
		id: 'shibui',
		romaji: 'Shibui',
		texts: {
			ja: '渋い',
			en: 'Simple, subtle, refined taste',
			es: 'Gusto simple, sutil, refinado',
			fr: 'Goût simple, subtil, raffiné',
			de: 'Einfacher, subtiler, raffinierter Geschmack',
			pt: 'Gosto simples, sutil, refinado',
		},
	},
	{
		id: 'aware-sa',
		romaji: 'Kanashimi',
		texts: {
			ja: '哀しみ',
			en: 'Profound sadness, pathos',
			es: 'Tristeza profunda, patetismo',
			fr: 'Tristesse profonde, pathos',
			de: 'Tiefe Traurigkeit, Pathos',
			pt: 'Tristeza profunda, páthos',
		},
	},
	{
		id: 'fuzei',
		romaji: 'Fūzei',
		texts: {
			ja: '風情',
			en: 'Aesthetic ambiance, taste',
			es: 'Ambiente estético, gusto',
			fr: 'Ambiance esthétique, goût',
			de: 'Ästhetisches Ambiente, Geschmack',
			pt: 'Ambiente estético, gosto',
		},
	},
	{
		id: 'miyabi',
		romaji: 'Miyabi',
		texts: {
			ja: '雅',
			en: 'Elegance, courtly refinement',
			es: 'Elegancia, refinamiento cortés',
			fr: 'Élégance, raffinement courtois',
			de: 'Eleganz, höfische Verfeinerung',
			pt: 'Elegância, refinamento cortês',
		},
	},
	{
		id: 'iki',
		romaji: 'Iki',
		texts: {
			ja: '粋',
			en: 'Chic, stylish sophistication',
			es: 'Sofisticación elegante',
			fr: 'Sophistication élégante',
			de: 'Schicke Raffinesse',
			pt: 'Sofisticação elegante',
		},
	},
	{
		id: 'sabi',
		romaji: 'Sabi',
		texts: {
			ja: '寂',
			en: 'Beauty of aging and wear',
			es: 'Belleza del envejecimiento',
			fr: 'Beauté du vieillissement',
			de: 'Schönheit des Alterns',
			pt: 'Beleza do envelhecimento',
		},
	},
	{
		id: 'wabi',
		romaji: 'Wabi',
		texts: {
			ja: '侘',
			en: 'Rustic simplicity, tranquility',
			es: 'Simplicidad rústica, tranquilidad',
			fr: 'Simplicité rustique, tranquillité',
			de: 'Rustikale Einfachheit, Ruhe',
			pt: 'Simplicidade rústica, tranquilidade',
		},
	},
	{
		id: 'kouyou',
		romaji: 'Kōyō',
		texts: {
			ja: '紅葉',
			en: 'Autumn leaves, fall foliage',
			es: 'Hojas de otoño, follaje otoñal',
			fr: 'Feuilles d\'automne, feuillage automnal',
			de: 'Herbstlaub, Herbstlaub',
			pt: 'Folhas de outono, folhagem outonal',
		},
	},
	{
		id: 'nagomi',
		romaji: 'Nagomi',
		texts: {
			ja: '和み',
			en: 'Harmony, peacefulness, calm',
			es: 'Armonía, paz, calma',
			fr: 'Harmonie, paix, calme',
			de: 'Harmonie, Friedlichkeit, Ruhe',
			pt: 'Harmonia, paz, calma',
		},
	},
	{
		id: 'shounen',
		romaji: 'Shōnen',
		texts: {
			ja: '少年',
			en: 'Boy, youth, young spirit',
			es: 'Chico, juventud, espíritu joven',
			fr: 'Garçon, jeunesse, esprit jeune',
			de: 'Junge, Jugend, junger Geist',
			pt: 'Garoto, juventude, espírito jovem',
		},
	},
	{
		id: 'yuutsu',
		romaji: 'Yūutsu',
		texts: {
			ja: '憂鬱',
			en: 'Melancholy, gloom, depression',
			es: 'Melancolía, tristeza, depresión',
			fr: 'Mélancolie, tristesse, dépression',
			de: 'Melancholie, Düsterkeit, Depression',
			pt: 'Melancolia, tristeza, depressão',
		},
	},
	{
		id: 'aware-mi',
		romaji: 'Aimai',
		texts: {
			ja: '曖昧',
			en: 'Ambiguous, vague, unclear',
			es: 'Ambiguo, vago, poco claro',
			fr: 'Ambigu, vague, flou',
			de: 'Mehrdeutig, vage, unklar',
			pt: 'Ambíguo, vago, incerto',
		},
	},
	{
		id: 'tamashii',
		romaji: 'Tamashii',
		texts: {
			ja: '魂',
			en: 'Soul, spirit, essence',
			es: 'Alma, espíritu, esencia',
			fr: 'Âme, esprit, essence',
			de: 'Seele, Geist, Essenz',
			pt: 'Alma, espírito, essência',
		},
	},
	{
		id: 'setsunai',
		romaji: 'Setsunai',
		texts: {
			ja: '切ない',
			en: 'Painful, heartwrenching',
			es: 'Doloroso, desgarrador',
			fr: 'Douloureux, déchirant',
			de: 'Schmerzhaft, herzzerreißend',
			pt: 'Doloroso, comovente',
		},
	},
	{
		id: 'kokoro',
		romaji: 'Kokoro',
		texts: {
			ja: '心',
			en: 'Heart, mind, spirit, feeling',
			es: 'Corazón, mente, espíritu, sentimiento',
			fr: 'Cœur, esprit, sentiment',
			de: 'Herz, Geist, Gefühl',
			pt: 'Coração, mente, espírito, sentimento',
		},
	},
	{
		id: 'kizuna',
		romaji: 'Kizuna',
		texts: {
			ja: '絆',
			en: 'Bonds between people',
			es: 'Lazos entre personas',
			fr: 'Liens entre les personnes',
			de: 'Verbindungen zwischen Menschen',
			pt: 'Laços entre pessoas',
		},
	},
	{
		id: 'shiawase',
		romaji: 'Shiawase',
		texts: {
			ja: '幸せ',
			en: 'Happiness, good fortune',
			es: 'Felicidad, buena fortuna',
			fr: 'Bonheur, bonne fortune',
			de: 'Glück, gutes Schicksal',
			pt: 'Felicidade, boa sorte',
		},
	},
	{
		id: 'wa',
		romaji: 'Wa',
		texts: {
			ja: '和',
			en: 'Harmony, peace, balance',
			es: 'Armonía, paz, equilibrio',
			fr: 'Harmonie, paix, équilibre',
			de: 'Harmonie, Frieden, Gleichgewicht',
			pt: 'Harmonia, paz, equilíbrio',
		},
	},
]

export const PHRASES_BY_CATEGORY: Record<PhraseCategory, Phrase[]> = {
	motivation: MOTIVATIONS,
	affirmation: AFFIRMATIONS,
	haiku: HAIKUS,
	word: WORDS,
}
